### ISSUE TITLE
'install_mode' error

### ISSUE THREAD

**Issue by tacman** [jalefkowit/virtualpress#2]
New to ansible, so not sure if this is an error on my machine or what.  Ubuntu 16.04.

tac@tac-wild-dog-desktop:/var/www/virtualpress$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

ansible local provisioner:
* The following settings shouldn't exist: install_mode

**Comment by jalefkowit** [comment]
Make sure your installed version of Vagrant is up to date, local provisioning with Ansible is a relatively new feature. The most recent version is 2.0.1.

**Comment by tacman** [comment]
Yep, that worked.  2.0.1 is available here: https://www.vagrantup.com/downloads.html
